apiVersion: batch/v1
kind: CronJob
metadata:
  name: compute-gardener-batch-job
spec:
  # Run every 30 minutes
  schedule: "*/30 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # Higher thresholds for batch jobs since they're more flexible
            compute-gardener-scheduler.kubernetes.io/carbon-intensity-threshold: "150.0"
        spec:
          schedulerName: compute-gardener-scheduler
          containers:
          - name: hpl-benchmark
            image: edwardchalstrey/hpl_benchmark
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
          restartPolicy: Never
