apiVersion: batch/v1
kind: Job
metadata:
  name: compute-gardener-job
spec:
  # Retry up to 2 times if scheduling constraints aren't met
  backoffLimit: 2
  template:
    metadata:
      annotations:
        # Higher thresholds for batch jobs that can be delayed
        compute-gardener-scheduler.kubernetes.io/carbon-intensity-threshold: "350.0"
        compute-gardener-scheduler.kubernetes.io/price-threshold: "0.25"
    spec:
      schedulerName: compute-gardener-scheduler
      containers:
      - name: data-processor
        image: data-processor:1.0
        command:
        - /process.sh
        - /data/input
        - /data/output
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        volumeMounts:
        - name: input-data
          mountPath: /data/input
          readOnly: true
        - name: output-data
          mountPath: /data/output
      volumes:
      - name: input-data
        persistentVolumeClaim:
          claimName: input-data-pvc
      - name: output-data
        persistentVolumeClaim:
          claimName: output-data-pvc
      # Don't restart on failure, let the job controller handle retries
      restartPolicy: Never
