apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compute-gardener-statefulset
  labels:
    app: database
spec:
  serviceName: "database"
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
      annotations:
        # Higher threshold for database pods since they're more sensitive to scheduling delays
        compute-gardener-scheduler.kubernetes.io/carbon-intensity-threshold: "350.0"
        compute-gardener-scheduler.kubernetes.io/price-threshold: "0.25"
    spec:
      schedulerName: compute-gardener-scheduler
      terminationGracePeriodSeconds: 60
      containers:
      - name: postgresql
        image: postgres:14
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_PASSWORD
          value: "example"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
