apiVersion: v1
kind: Pod
metadata:
  name: test-power-metrics
spec:
  schedulerName: compute-gardener-scheduler  # Use our scheduler
  restartPolicy: Never
  containers:
  - name: test
    image: gcr.io/k8s-staging-perf-tests/sleep:latest  # Simple image that can use CPU
    command: 
    - "/bin/sh"
    - "-c"
    - |
      # Generate some CPU load
      for i in $(seq 1 1000000); do
        echo "scale=10; 4*a(1)" | bc -l >/dev/null
      done
      echo "Done generating load"
    resources:
      requests:
        cpu: "200m"
      limits:
        cpu: "500m"  # Higher limit to allow CPU load generation
