# Default values for compute-gardener-scheduler
# This is a YAML-formatted file

# Note: Use Helm's --namespace and --create-namespace flags 
# to specify the installation namespace

# General scheduler configuration
scheduler:
  # Scheduler mode: "secondary" (default) or "primary"
  # - secondary: runs alongside default scheduler, only handles pods that explicitly set schedulerName
  # - primary: acts as the default scheduler for all pods (not recommended for general use)
  mode: "secondary"
  name: compute-gardener-scheduler
  image: docker.io/dmasselink/compute-gardener-scheduler:v0.1.4-fa4ec13
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  leaderElect: false
  # Maximum time to delay pod scheduling when waiting for better conditions (price or carbon)
  maxSchedulingDelay: "24h"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: ""
  
  # Probe configuration
  probes:
    livenessProbe:
      initialDelaySeconds: 15
    readinessProbe:
      initialDelaySeconds: 15

# Carbon-aware scheduling configuration
carbonAware:
  enabled: true
  carbonIntensityThreshold: 200.0
  electricityMap:
    apiKey: "YOUR_ELECTRICITY_MAP_API_KEY" # Change this or use --set-string
    # Additional electricity map settings can be added here

# Price-aware scheduling configuration
priceAware:
  enabled: false
  provider: "tou" # Time of Use
  schedules:
    # Monday-Friday peak pricing periods (4pm-9pm)
    - dayOfWeek: "1-5"
      startTime: "16:00"
      endTime: "21:00"
      peakRate: 0.30
      offPeakRate: 0.10
    # Weekend peak pricing periods (1pm-7pm)
    - dayOfWeek: "0,6"
      startTime: "13:00"
      endTime: "19:00"
      peakRate: 0.30
      offPeakRate: 0.10

# Metrics configuration
metrics:
  # Set to false to disable all metrics-related resources (Service and ServiceMonitor)
  # This avoids dependencies on Prometheus Operator CRDs for simple installations
  enabled: true
  port: 10259
  service:
    enabled: true
    port: 10259
  serviceMonitor:
    enabled: true
    namespace: "monitoring" # Default Prometheus namespace, change to match your setup
    interval: "15s" # Match the CPU exporter's sampling interval
    insecureSkipVerify: true # For testing only, consider proper CA verification in prod

# Sample pod to demonstrate scheduler usage
samplePod:
  # When enabled, creates a sample pod that demonstrates scheduler functionality
  # The pod also helps validate metrics collection with a longer-running workload
  # If you see "Zero or negative energy value" warnings in logs, the pod may not 
  # have run long enough to collect meaningful metrics
  enabled: true
  image: "busybox:latest"

# Hardware profiles for power estimation
hardwareProfiles:
  enabled: true
  mountPath: "/etc/kubernetes/compute-gardener-scheduler/hardware-profiles"

# Node exporter configuration for hardware metrics 
nodeExporter:
  # Enable the hardware metrics exporter DaemonSet for accurate CPU/GPU model detection and power measurements
  # Note: For GPU metrics, requires nodes with NVIDIA GPUs and nvidia-smi installed
  enabled: false
  image: docker.io/dmasselink/compute-gardener-node-exporter:v0.1.4-fa4ec13
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 100Mi
  # Port for metrics endpoint
  metricsPort: 9100
  # Log verbosity level (0-5)
  logLevel: 2

# Additional plugin configuration
plugins:
  # Can be expanded with further plugin-specific configuration
  pluginConfig: []
