apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "compute-gardener-scheduler.fullname" . }}-hw-profiles
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "compute-gardener-scheduler.labels" . | nindent 4 }}
data:
  hardware-profiles.yaml: |
    # CPU model mappings from NFD labels to specific CPU models
    # These mappings help identify exact CPU models from NFD-provided information
    cpuModelMappings:
      # Intel CPU mappings
      Intel:
        # Intel Xeon Cascade Lake
        "6-85": "Intel(R) Xeon(R) Platinum 8275CL"
        # Intel Xeon Skylake
        "6-85-2": "Intel(R) Xeon(R) Platinum 8175M"
        "6-85-3": "Intel(R) Xeon(R) Platinum 8124M"
        "6-85-4": "Intel(R) Xeon(R) Gold 6148"
        "6-85-5": "Intel(R) Xeon(R) Platinum 8168"
        # Intel Xeon Broadwell
        "6-79": "Intel(R) Xeon(R) E5-2686 v4"
        "6-79-1": "Intel(R) Xeon(R) E5-2690 v4"
        "6-79-2": "Intel(R) Xeon(R) E5-2673 v4"
        # Intel Xeon Haswell
        "6-63": "Intel(R) Xeon(R) E5-2676 v3"
        # Intel Skylake Client
        "6-94": "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz"
        # Intel Coffee Lake
        "6-158": "Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz"
        "6-158-1": "Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz"
        # Intel Alder Lake
        "6-151": "12th Gen Intel(R) Core(TM) i5-12600K"
        "6-151-2": "12th Gen Intel(R) Core(TM) i9-12900KF"
        # Skylake Client and Kaby Lake
        "6-142": "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz"
        "6-142-1": "Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz"
        # Fallbacks
        "6": "Intel(R) Xeon(R) CPU @ 2.20GHz"

      # AMD CPU mappings
      AMD:
        # EPYC Rome
        "23-49": "AMD EPYC 7B12"
        "23-49-1": "AMD EPYC 7R32"
        "23-49-2": "AMD EPYC 7571"
        # EPYC Milan
        "25-1": "AMD EPYC 7R13"
        "25-1-1": "AMD EPYC 7763"
        # Ryzen 3rd Gen (Zen 2)
        "23-113": "AMD Ryzen 5 3600 6-Core Processor"
        # Ryzen 5th Gen (Zen 3)
        "25-33": "AMD Ryzen 7 5800X 8-Core Processor"
        # Fallbacks
        "23": "AMD EPYC 7B12"
        "25": "AMD EPYC 7R13"

      # ARM CPU mappings
      ARM:
        # Raspberry Pi 4B
        "15-53379": "Raspberry Pi 4 Model B (BCM2711)"
        # ARM Server CPUs - Neoverse
        "8-1": "ARM Neoverse N1"
        "8-2": "ARM Neoverse V1"
        "8-10": "Ampere Altra Q80-30"
        # Generic ARM fallbacks
        "15": "ARM Cortex-A72"
        "8": "ARM Neoverse N1"

    # CPU power profiles - identifier -> power characteristics
    cpuProfiles:
      # Intel CPUs - Server/Cloud
      "Intel(R) Xeon(R) Platinum 8175M":
        idlePower: 10.0
        maxPower: 115.0
        numCores: 24
        baseFrequencyGHz: 2.5
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.5
      "Intel(R) Xeon(R) Platinum 8275CL":
        idlePower: 10.5
        maxPower: 120.0
        numCores: 24
        baseFrequencyGHz: 2.5
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.6
      "Intel(R) Xeon(R) Platinum 8124M":
        idlePower: 12.0
        maxPower: 150.0
        numCores: 18
        baseFrequencyGHz: 3.0
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.5
      "Intel(R) Xeon(R) E5-2686 v4":
        idlePower: 9.0
        maxPower: 95.0
        numCores: 8
        baseFrequencyGHz: 2.3
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.0
      "Intel(R) Xeon(R) E5-2676 v3":
        idlePower: 8.5
        maxPower: 85.0
        numCores: 12
        baseFrequencyGHz: 2.4
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.3
      "Intel(R) Xeon(R) E5-2673 v4":
        idlePower: 8.8
        maxPower: 90.0
        numCores: 20
        baseFrequencyGHz: 2.3
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.5
      "Intel(R) Xeon(R) E5-2690 v4":
        idlePower: 9.2
        maxPower: 100.0
        numCores: 14
        baseFrequencyGHz: 2.6
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.5
      "Intel(R) Xeon(R) Gold 6148":
        idlePower: 11.0
        maxPower: 125.0
        numCores: 20
        baseFrequencyGHz: 2.4
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.7
      "Intel(R) Xeon(R) Platinum 8168":
        idlePower: 12.5
        maxPower: 155.0
        numCores: 24
        baseFrequencyGHz: 2.7
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.7
      
      # Intel CPUs - Consumer/Edge (Homelab)
      "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz":
        idlePower: 5.0
        maxPower: 65.0
        numCores: 4
        baseFrequencyGHz: 3.2
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.8
          max: 3.6
      "Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz":
        idlePower: 5.0
        maxPower: 35.0
        numCores: 4
        baseFrequencyGHz: 2.5
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.8
          max: 3.0
      "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz":
        idlePower: 8.0
        maxPower: 95.0
        numCores: 6
        baseFrequencyGHz: 3.2
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.8
          max: 4.6
      "Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz":
        idlePower: 9.0
        maxPower: 105.0
        numCores: 8
        baseFrequencyGHz: 3.6
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.8
          max: 4.9
      "Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz":
        idlePower: 10.0
        maxPower: 125.0
        numCores: 8
        baseFrequencyGHz: 3.6
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.8
          max: 5.0
      "12th Gen Intel(R) Core(TM) i5-12600K":
        idlePower: 9.5
        maxPower: 125.0
        numCores: 10
        baseFrequencyGHz: 3.7
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.8
          max: 4.9
      "12th Gen Intel(R) Core(TM) i9-12900KF":
        idlePower: 15.0
        maxPower: 241.0
        numCores: 16
        baseFrequencyGHz: 3.2
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.8
          max: 5.2
      
      # AMD CPUs - Server/Cloud
      "AMD EPYC 7B12":
        idlePower: 10.5
        maxPower: 125.0
        numCores: 24
        baseFrequencyGHz: 2.45
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.5
          max: 3.3
      "AMD EPYC 7R32":
        idlePower: 11.0
        maxPower: 130.0
        numCores: 32
        baseFrequencyGHz: 2.9
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.5
          max: 3.3
      "AMD EPYC 7571":
        idlePower: 10.0
        maxPower: 120.0
        numCores: 32
        baseFrequencyGHz: 2.2
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.5
          max: 3.0
      "AMD EPYC 7R13":
        idlePower: 11.5
        maxPower: 140.0
        numCores: 32
        baseFrequencyGHz: 2.6
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.5
          max: 3.6
      "AMD EPYC 7763":
        idlePower: 12.5
        maxPower: 160.0
        numCores: 64
        baseFrequencyGHz: 2.45
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.5
          max: 3.5
          
      # Generic Intel Xeon for Google Cloud/GKE
      "Intel(R) Xeon(R) CPU @ 2.20GHz":
        idlePower: 10.0
        maxPower: 110.0
        numCores: 16
        baseFrequencyGHz: 2.2
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.2
          max: 3.0
      
      # AMD CPUs - Consumer/Edge (Homelab)
      "AMD Ryzen 5 3600 6-Core Processor":
        idlePower: 6.0
        maxPower: 65.0
        numCores: 6
        baseFrequencyGHz: 3.6
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 2.2
          max: 4.2
      "AMD Ryzen 7 5800X 8-Core Processor":
        idlePower: 8.0
        maxPower: 105.0
        numCores: 8
        baseFrequencyGHz: 3.8
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 2.8
          max: 4.7
          
      # ARM CPUs - Consumer/Edge (Homelab)
      "Raspberry Pi 4 Model B (BCM2711)":
        idlePower: 2.0
        maxPower: 6.0
        numCores: 4
        baseFrequencyGHz: 1.5
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.6
          max: 1.8
      "ARM Cortex-A72":
        idlePower: 1.8
        maxPower: 5.5
        numCores: 4
        baseFrequencyGHz: 1.5
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 0.6
          max: 1.7
          
      # ARM CPUs - Server/Cloud
      "ARM Neoverse N1":
        idlePower: 8.0
        maxPower: 80.0
        numCores: 64
        baseFrequencyGHz: 2.6
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.0
          max: 3.0
      "ARM Neoverse V1":
        idlePower: 10.0
        maxPower: 95.0
        numCores: 64
        baseFrequencyGHz: 2.8
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.0
          max: 3.5
      "Ampere Altra Q80-30":
        idlePower: 12.0
        maxPower: 150.0
        numCores: 80
        baseFrequencyGHz: 3.0
        powerScaling: "quadratic"
        frequencyRangeGHz:
          min: 1.0
          max: 3.3
    
    # GPU power profiles - identifier -> power characteristics
    gpuProfiles:
      # NVIDIA GPUs - Data Center
      "NVIDIA A100":
        idlePower: 25.0
        maxPower: 400.0
      "NVIDIA T4":
        idlePower: 10.0
        maxPower: 70.0
      "NVIDIA V100":
        idlePower: 30.0
        maxPower: 300.0
      "NVIDIA K80":
        idlePower: 15.0
        maxPower: 150.0
      "NVIDIA A10G":
        idlePower: 20.0
        maxPower: 230.0
      
      # NVIDIA GPUs - Consumer
      "NVIDIA GeForce RTX 3080":
        idlePower: 20.0
        maxPower: 320.0
      "NVIDIA GeForce GTX 1080 Ti":
        idlePower: 15.0
        maxPower: 250.0
      "NVIDIA GeForce GTX 1660":
        idlePower: 7.0
        maxPower: 125.0
      "NVIDIA GeForce RTX 3060":
        idlePower: 12.0
        maxPower: 170.0
    
    # Memory power profiles - memory type -> power characteristics
    memProfiles:
      # Server Memory
      "DDR4-2666 ECC":
        idlePowerPerGB: 0.125
        maxPowerPerGB: 0.375
        baseIdlePower: 1.0
      "DDR4-3200 ECC":
        idlePowerPerGB: 0.15
        maxPowerPerGB: 0.45
        baseIdlePower: 1.2
      "DDR5-4800 ECC":
        idlePowerPerGB: 0.11
        maxPowerPerGB: 0.33
        baseIdlePower: 0.9
      
      # Desktop/Consumer Memory
      "DDR4-2400":
        idlePowerPerGB: 0.1
        maxPowerPerGB: 0.3
        baseIdlePower: 0.8
      "DDR4-3200":
        idlePowerPerGB: 0.12
        maxPowerPerGB: 0.36
        baseIdlePower: 1.0
      "DDR4-3600":
        idlePowerPerGB: 0.14
        maxPowerPerGB: 0.42
        baseIdlePower: 1.1
      "DDR5-5200":
        idlePowerPerGB: 0.1
        maxPowerPerGB: 0.3
        baseIdlePower: 0.8

    # Cloud instance type mappings to hardware components
    cloudInstanceMapping:
      # AWS instance types
      aws:
        "m5.large":
          cpuModel: "Intel(R) Xeon(R) Platinum 8175M"
          memoryType: "DDR4-2666 ECC"
          totalMemory: 8192
          memChannels: 6
        "m5.xlarge":
          cpuModel: "Intel(R) Xeon(R) Platinum 8175M"
          memoryType: "DDR4-2666 ECC"
          totalMemory: 16384
        "m5.2xlarge":
          cpuModel: "Intel(R) Xeon(R) Platinum 8175M"
          memoryType: "DDR4-2666 ECC"
          totalMemory: 32768
        "c5.large":
          cpuModel: "Intel(R) Xeon(R) Platinum 8124M"
          memoryType: "DDR4-2666 ECC"
          totalMemory: 4096
        "c5.xlarge":
          cpuModel: "Intel(R) Xeon(R) Platinum 8124M"
          memoryType: "DDR4-2666 ECC"
          totalMemory: 8192
        "p3.2xlarge":
          cpuModel: "Intel(R) Xeon(R) E5-2686 v4"
          gpuModel: "NVIDIA V100"
          memoryType: "DDR4-2666 ECC"
          numGPUs: 1
          totalMemory: 61440
      
      # GCP instance types
      gcp:
        "default-gke-profile":
          cpuModel: "Intel(R) Xeon(R) CPU @ 2.20GHz"
          numCores: 16
          totalMemory: 32768
          memoryType: "DDR4-2666 ECC"
        "n2-standard-2":
          cpuModel: "Intel(R) Xeon(R) Gold 6148"
          numCores: 2
          totalMemory: 8192
          memoryType: "DDR4-2666 ECC"
        "n2-standard-4":
          cpuModel: "Intel(R) Xeon(R) Gold 6148"
          numCores: 4
          totalMemory: 16384
          memoryType: "DDR4-2666 ECC"
        "n2-standard-8":
          cpuModel: "Intel(R) Xeon(R) Gold 6148"
          numCores: 8
          totalMemory: 32768
          memoryType: "DDR4-2666 ECC"
        "c2-standard-4":
          cpuModel: "Intel(R) Xeon(R) Platinum 8168"
          numCores: 4
          totalMemory: 16384
          memoryType: "DDR4-2666 ECC"
        "a2-highgpu-1g":
          cpuModel: "AMD EPYC 7B12"
          gpuModel: "NVIDIA A100"
          numCores: 12
          numGPUs: 1
          totalMemory: 86016
          memoryType: "DDR4-3200 ECC"
      
      # Azure instance types
      azure:
        "Standard_D2s_v3":
          cpuModel: "Intel(R) Xeon(R) E5-2673 v4"
          numCores: 2
          totalMemory: 8192
        "Standard_D4s_v3":
          cpuModel: "Intel(R) Xeon(R) E5-2673 v4"
          numCores: 4
          totalMemory: 16384
        "Standard_F8s_v2":
          cpuModel: "Intel(R) Xeon(R) Platinum 8168"
          numCores: 8
          totalMemory: 16384
        "Standard_NC6s_v3":
          cpuModel: "Intel(R) Xeon(R) E5-2690 v4"
          gpuModel: "NVIDIA V100"
          numCores: 6
          numGPUs: 1
          totalMemory: 114688
