apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scheduler.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.scheduler.name }}-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      {{- if eq .Values.scheduler.mode "primary" }}
      # PRIMARY MODE: Acts as the default scheduler for ALL pods in the cluster
      # (not recommended for general use)
      - schedulerName: default-scheduler
        plugins:
          preFilter:
            enabled:
              - name: ComputeGardenerScheduler
          filter:
            enabled:
              - name: ComputeGardenerScheduler
      {{- end }}
      # SECONDARY MODE: Only handles pods that explicitly set schedulerName
      - schedulerName: {{ .Values.scheduler.name }}
        plugins:
          preFilter:
            enabled:
              - name: ComputeGardenerScheduler
          filter:
            enabled:
              - name: ComputeGardenerScheduler
    # Leader election configuration - determines whether this scheduler
    # participates in leader election with other scheduler instances
    leaderElection:
      leaderElect: {{ .Values.scheduler.leaderElect }}
{{- if .Values.priceAware.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scheduler.name }}-pricing-schedules
  namespace: {{ .Release.Namespace }}
data:
  pricing-schedules.yaml: |
    schedules:
      {{- range .Values.priceAware.schedules }}
      - dayOfWeek: "{{ .dayOfWeek }}"
        startTime: "{{ .startTime }}"
        endTime: "{{ .endTime }}"
        peakRate: {{ .peakRate }}
        offPeakRate: {{ .offPeakRate }}
      {{- end }}
{{- end }}