{{- if and .Values.metrics.enabled .Values.metrics.gpuMetrics.enabled (not .Values.metrics.gpuMetrics.external) }}
{{- /* Standard constants for NVIDIA GPU setup */}}
{{- $gpuNodeSelector := dict "nvidia.com/gpu" "present" }}
{{- $gpuRuntimeClassName := "nvidia" }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: compute-gardener-dcgm-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: compute-gardener-dcgm-exporter
    component: gpu-metrics
    part-of: compute-gardener-scheduler
    {{- include "compute-gardener-scheduler.exporterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: compute-gardener-dcgm-exporter
  template:
    metadata:
      labels:
        app: compute-gardener-dcgm-exporter
        component: gpu-metrics
        part-of: compute-gardener-scheduler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.gpuMetrics.port }}"
        prometheus.io/path: "/metrics"
    spec:
      # Standard nodeSelector for NVIDIA GPU nodes
      nodeSelector:
        {{- toYaml $gpuNodeSelector | nindent 8 }}
      # Standard runtimeClassName for NVIDIA GPU access
      runtimeClassName: {{ $gpuRuntimeClassName }}
      containers:
      - name: exporter
        image: {{ .Values.metrics.gpuMetrics.image }}
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "utility"
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          privileged: true
        ports:
        - containerPort: {{ .Values.metrics.gpuMetrics.port }}
          name: metrics
          protocol: TCP
        volumeMounts:
        - name: nvidia-driver
          mountPath: /usr/local/nvidia
        - name: nvidia-driver-run
          mountPath: /run/nvidia/driver
        - name: dev
          mountPath: /dev
      volumes:
      - name: nvidia-driver
        hostPath:
          path: /usr/local/nvidia
      - name: nvidia-driver-run
        hostPath:
          path: /run/nvidia/driver
      - name: dev
        hostPath:
          path: /dev
      # These tolerations ensure the DaemonSet runs on GPU nodes, which might have taints
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: compute-gardener-dcgm-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: compute-gardener-dcgm-exporter
    component: gpu-metrics
    part-of: compute-gardener-scheduler
    {{- include "compute-gardener-scheduler.exporterLabels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.gpuMetrics.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.metrics.gpuMetrics.port }}
    targetPort: {{ .Values.metrics.gpuMetrics.port }}
    protocol: TCP
    name: metrics
  selector:
    app: compute-gardener-dcgm-exporter
{{- if and .Values.metrics.gpuMetrics.serviceMonitor.enabled .Values.metrics.serviceMonitor.enabled }}
---
{{- if .Values.metrics.gke }}
# GKE-specific monitoring
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: compute-gardener-dcgm-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: compute-gardener-dcgm-exporter
    component: gpu-metrics
    part-of: compute-gardener-scheduler
    {{- include "compute-gardener-scheduler.exporterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: compute-gardener-dcgm-exporter
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.gpuMetrics.serviceMonitor.interval }}
    path: /metrics
{{- else }}
# Standard Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: compute-gardener-dcgm-exporter
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    app: compute-gardener-dcgm-exporter
    component: gpu-metrics
    part-of: compute-gardener-scheduler
    {{- include "compute-gardener-scheduler.exporterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: compute-gardener-dcgm-exporter
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.gpuMetrics.serviceMonitor.interval }}
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}