{{- if .Values.samplePod.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.scheduler.name }}-sample-pod
  namespace: default
  labels:
    {{- include "compute-gardener-scheduler.labels" . | nindent 4 }}
    component: sample-pod
  annotations:
    compute-gardener-scheduler.kubernetes.io/skip: "true"
spec:
  schedulerName: {{ .Values.scheduler.name }}
  restartPolicy: Never
  containers:
  - name: pause
    image: {{ .Values.samplePod.image }}
    command:
    - /bin/sh
    - -c
    # Run a longer workload to allow metrics collection if enabled
    - "echo 'This pod was scheduled by the {{ .Values.scheduler.name }}' && echo 'Running CPU workload to generate metrics (if metrics collection is enabled)...' && i=1; while [ $i -le 60 ]; do echo $(($i*$i)) > /dev/null; sleep 2; i=$(($i+1)); done"
    resources:
      requests:
        cpu: 100m
        memory: 20Mi
      limits:
        cpu: 200m
        memory: 40Mi
{{- end }}