{{- if .Values.carbonAware.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scheduler.name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  electricity-map-api-key: {{ .Values.carbonAware.electricityMap.apiKey | b64enc }}
{{- end }}