{{- if .Values.carbonAware.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scheduler.name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  electricity-map-api-key: {{ .Values.carbonAware.electricityMap.apiKey | b64enc }}
  {{- if and (eq .Values.carbonAware.provider "cg-api") .Values.carbonAware.cgApi.apiKey }}
  cg-api-key: {{ .Values.carbonAware.cgApi.apiKey | b64enc }}
  {{- end }}
{{- end }}