name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod download

      - name: Install envtest
        run: make install-envtest

      - name: Run tests with coverage
        run: make unit-test-coverage

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(cat .coverage/coverage.txt | grep -o '[0-9.]\+%' | tr -d '%')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Coverage: $COVERAGE%"

      - name: Create badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: coverage
          LABEL: 'Coverage'
          STATUS: ${{ steps.coverage.outputs.coverage }}%
          COLOR: ${{ steps.coverage.outputs.coverage >= 80 && '5cb85c' || steps.coverage.outputs.coverage >= 70 && 'a3b858' || steps.coverage.outputs.coverage >= 50 && 'dfb317' || steps.coverage.outputs.coverage >= 30 && 'f0ad4e' || 'd9534f' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}